-- tables are refered to as sets when querying multiple tables
-- depending on how you use those sets of data it can be called different things
-- An intersection for example is using the data that the sets have in common
-- A difference is the opposite of an intersection, everything they don't have in common
-- A union is both full sets.